[[redirects]]
  from = "/robots.txt"
  to = "https://raw.githubusercontent.com/izulwahidin/Netlify-Reverse-Proxy/main/robots.txt"
  status = 200
  force = true
  
[[redirects]]
  from = "/*"
  to = "https://dev-wahidin.pantheonsite.io/:splat"
  status = 200
  force = true
  headers = {X-Robots-Tag = "index",izul = "wahidin"}

[[headers]]
  for = "/*"
  [headers.values]
  izul = "wahidin"
  x-robots-tag = "index"
